### ISSUE TITLE
Upgrade to `eslint-config-airbnb-base@14`

### ISSUE THREAD

**Issue by fafnirical** [vuejs/eslint-config-airbnb#1]
Per the [changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md#1400--2019-08-09), upstream also added support for `eslint` v6 and dropped `eslint` v4, as well as updated `eslint-plugin-import`. This would be a breaking change.

**Comment by sodatea** [comment]
v5.0.0 just got published.
