### ISSUE TITLE
使用 eslint-config-airbnb 报错问题

### ISSUE THREAD

**Issue by feiyu-git** [vuejs/eslint-config-airbnb#13]
应用场景：动态require模块时如下
this.handbook = require(`@/assets/md/${newVal}.md`);
会出现如下报错
![image](https://user-images.githubusercontent.com/57039329/99162322-6c625400-2737-11eb-8e80-a576e64ff94c.png)

【(parameter) newVal: any
Calls to require() should use string literalseslintimport/no-dynamic-require
Unexpected require().eslintglobal-require】
请问如何解决

**Comment by sodatea** [comment]
这种用法是 Airbnb 规范里禁止的。
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-dynamic-require.md

请改用 `import` 来动态引入模块。
或者加注释临时禁用这条规则 `// eslint-disable-line import/no-dymanic-require`
