### ISSUE TITLE
[question] Typescript support?

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/eslint-config-airbnb#23]
Is Typescript support on the roadmap? There's a [`eslint-config-airbnb-typescript`](https://github.com/iamturns/eslint-config-airbnb-typescript) config - I wonder if you could use it instead of `eslint-config-airbnb-base`?

**Comment by undergroundwires** [comment]
I'd love to see TypeScript being supported here as first class-citizen knowing even Vue 3 is written in TypeScript.

Maybe `vuejs/eslint-config-airbnb-typescript` could be created? Either following the suggestion from OP or maybe just merging `rules` part of it.

What do you say @sodatea?

**Comment by undergroundwires** [comment]
I'd love to see TypeScript being supported here as first class-citizen knowing even Vue 3 is written in TypeScript.

Maybe `vuejs/eslint-config-airbnb-typescript` could be created? Either following the suggestion from OP or maybe just merging [`rules`](https://github.com/iamturns/eslint-config-airbnb-typescript/blob/d30b7d2a41f3f2cf899cad3ed69e3b7eacbc7234/lib/shared.js#L29-L253) part of it.

Would you consider it @sodatea?

**Comment by sodatea** [comment]
I'm working on that now.

**Comment by undergroundwires** [comment]
I see that that repository does not configure better import resolution for TypeScript. `import/` rules such as `import/order` does not work completely. There's a solution that solves that: [eslint-import-resolver-typescript](https://github.com/alexgorbatchev/eslint-import-resolver-typescript), it's popular project used by many and proved itself. It would be nice if we could consider configuring it as well.

**Comment by sodatea** [comment]
Here it is:
https://github.com/vuejs/eslint-config-airbnb/tree/v7.0.0/packages/eslint-config-airbnb-with-typescript#readme
