### ISSUE TITLE
use  eslint-config-airbnb with vite project

### ISSUE THREAD

**Issue by ronny1020** [vuejs/eslint-config-airbnb#28]
I try to use eslint-config-airbnb in a vite vue-ts project.
There is a error when I try to run eslint.

```
Error: Cannot read config file: (my project path)\node_modules\@vue\eslint-config-airbnb\index.js
Error: Cannot find module '@vue/cli-service/webpack.config.js'

```
Since it's vite project, I think webpack.config.js isn't required ?

 here is the versions for my project
   "vite": "^2.4.3",
    "@vue/eslint-config-airbnb": "^5.3.0",
    "eslint": "^7.19.0",
 
Is  eslint-config-airbnb current support to vue with vite? 

Thanks a lot!

**Comment by LinusBorg** [comment]
Please read the README in this repository. You will realize that this is a specialized config, for Vue CLI, which uses webpack.

**Comment by ronny1020** [comment]
I see.

I just think if it may also support for the vite like eslint-plugin-vue or @vue/eslint-config-prettier which is also used in the Vue Cli.

Thanks a lot.

**Comment by sodatea** [comment]
It's now possible with v6.0.0 as `@vue/cli-service` becomes an optional peer dependency.
