### ISSUE TITLE
Vue Plugins: no-param-reassign

### ISSUE THREAD

**Issue by iomariani** [vuejs/eslint-config-airbnb#29]
Hey guys, I'm currently writing some Vue plugins and I've noticed this config blocks `Vue` for `no-param-reassign`:

https://github.com/vuejs/eslint-config-airbnb/blob/cfa98d5f95be585d72e092f783178518cf3c0aa5/index.js#L29-L36

It states on the [documentation](https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin) that if we want to apply a instance method to be globally usable we should use:
```js
Vue.prototype.$method = ...
```

However if we want to apply this airbnb config while building a plugin we always need disable it manually.

```js
rules: {
  'no-param-reassign': ['error', {
      props: true,
      ignorePropertyModificationsFor: ['Vue'],
    },
  ],
},
```

Since this is only applicable on a vue plugin scenario, is it an intentional behavior to block it?

**Comment by sodatea** [comment]
Yes.
Feel free to override the rules as long as you know what you are doing.
But I'd recommend only disabling it in the plugin implementation, in case other collaborators of the project accidentally break the rule elsewhere.
