### ISSUE TITLE
Issue with link on NPM page

### ISSUE THREAD

**Issue by AndreasCag** [vuejs/eslint-config-airbnb#3]
[@vue/eslint-config-airbnb page](https://www.npmjs.com/package/@vue/eslint-config-airbnb) on NPM has link to vue-cli repo as a repository link:

![image](https://user-images.githubusercontent.com/14947036/68853309-bb237b00-06ea-11ea-9828-157148b2a865.png)

I expect, that repository link would be `https://github.com/vuejs/eslint-config-airbnb`.

Came up with the issue when tried to find source code of @vue/eslint-config-airbnb.

**Comment by sodatea** [comment]
The link was updated in the repository but the one on the npm registry won't be updated until a new version published, which I plan to do in the weeks ahead.

**Comment by AndreasCag** [comment]
Thanks <3

**Comment by sodatea** [comment]
Fixed with the release of v5.0.0
