### ISSUE TITLE
Support ESLint 8

### ISSUE THREAD

**Issue by daverogers** [vuejs/eslint-config-airbnb#33]
`"@vue/eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0 || ^7.2.0".`

Looks like the latest [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) supports `^8.2.0` so you just need a version bump

**Comment by sodatea** [comment]
Supported in v6.0.0
