### ISSUE TITLE
Identical peer and dev dependency 'eslint-plugin-vuejs-accessibility'

### ISSUE THREAD

**Issue by aleissner** [vuejs/eslint-config-airbnb#38]
I ran into a problem where a npm version wouldn't install eslint-plugin-vuejs-accessibility because it is listed as a peer dependency aswell as a devDependency.
Yes, I can fix that with a different npm version.
But it does not seem right to me to define the dependency this way. Listing the identical dependency as peer when it is already a dev dependency does not add anything.

**Comment by merlosy** [comment]
Hi! I had an issue related to this as well:
Running `npx eslint --print-config src/app.vue > eslintconfig.json` failed with the following
```sh
Oops! Something went wrong! :(

ESLint: 8.18.0

ESLint couldn't find the plugin "eslint-plugin-vuejs-accessibility".

(The package "eslint-plugin-vuejs-accessibility" was not found when loaded as a Node module from the directory "D:\git-workspace\my-project".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-vuejs-accessibility@latest --save-dev

The plugin "eslint-plugin-vuejs-accessibility" was referenced from the config file in ".eslintrc.js » @vue/eslint-config-airbnb".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

**Comment by sodatea** [comment]
That's how peer dependency works:
It won't be automatically installed in *this* project unless you also specify it as a dependency or dev dependency.

So when authoring this package, we need to install it as a dev dependency to test it.
It IS A COMMON PRACTICE to have identical packages in `peerDependencies` and `devDependencies`.

Besides, `devDependencies` won't be automatically installed in the users' projects. Only `dependencies` are transitive.

---

Anyway, this is no longer an issue in v7.0.0. All plugins are dependencies now.
