### ISSUE TITLE
How to disable accessibility?

### ISSUE THREAD

**Issue by 9mm** [vuejs/eslint-config-airbnb#42]
I'm using:

`"@vue/eslint-config-airbnb": "^6.0.0",`

for an internal app but I don't want to get nagged by the tons of accessibility rules, how can I still use airbnb defaults but disable accessibility without adding every single rule?

**Comment by bananna0** [comment]
I have the same question here

**Comment by bananna0** [comment]
@9mm Thank you for this workaround;)

But it would be better to have some one command or any setting to turn it off(

**Comment by 9mm** [comment]
@bananna0 yep, I thought the same thing until I just couldn't take the warnings for every single image and title anymore and caved in

**Comment by sodatea** [comment]
> But it would be better to have some one command or any setting to turn it off(

It's an intentional decision to make it hard to disable. Developers *should* make accessible websites.

The upstream [`eslint-config-airbnb`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) library didn't provide an easy way to turn off these rules, either.

**Comment by martijnvanloonafs** [comment]
Oke i will use another library
