### ISSUE TITLE
Missing webpack package dependency when using Yarn

### ISSUE THREAD

**Issue by RCVarley** [vuejs/eslint-config-airbnb#5]
I'm new to yarn and I've started a vue project with Yarn 2 (berry) with PnP and it's complaining about a missing package dependency. I'm happy to submit a pull request my proposed solution, but I figured I'd check here first.

## Basic Structure
```
my-package
├── webpack@^4.43.0
└── @vue/eslint-config-airbnb
    ├── @vue/cli-service@^3.0.0 || ^4.0.0-0 (peer)
    ├── @vue/cli-service@4.1.2 (dev)
    └── eslint-import-resolver-webpack
        └── webpack@>=1.11.0 (peer) 
```

## The Situation
1. `my-package` depends on `@vue/eslint-config-airbnb`.
2. `yarn install` elicits the following warning:
```
@vue/eslint-config-airbnb@npm:5.0.2 [0c8ee] doesn't provide webpack@>=1.11.0 requested by eslint-import-resolver-webpack@npm:0.11.1
```
3. `eslint-import-resolver-webpack` has a **peer** dependency of `"webpack": ">=1.11.0"`
4. `@vue/eslint-config-airbnb` has:
    1. A **dependency** of `"eslint-import-resolver-webpack": "^0.11.1"
    2. **No** dependency of `webpack`
5. `yarn install` in `@vue/eslint-config-airbnb` elicits the following response:
```
...
[3/4] Linking dependencies...
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning " > @vue/cli-service@4.1.2" has unmet peer dependency "vue-template-compiler@^2.0.0".
[4/4] Building fresh packages...
...
```

> Note: I'm not sure why, [vue/cli-service@4.1.2](https://github.com/vuejs/vue-cli/blob/v4.1.2/package.json) specifies `vue-template-compiler@^2.6.10` as a resolution.

## The Proposed Solution
I think that the solution here is to add **dev** dependencies of `webpack@>=1.11.0` and `vue-template-compiler@^2.0.0`.

## Edits
- Added more lines to warning message, including the dependency on vue-template-compiler.
- Added vue-template-compiler versions to basic structure
- Changed proposed solution to add ~~dependencies~~ devDependencies instead of peer dependencies, because it didn't remove the warning.

**Comment by sodatea** [comment]
Fixed in v7 as we no longer depend on `eslint-import-resolver-webpack`.
