### ISSUE TITLE
Upgrade @eslint-typescript to v6

### ISSUE THREAD

**Issue by frsimond** [vuejs/eslint-config-airbnb#58]
If I use this package with the latest typescript and vue versions (ie: 5.1.x and 3.3.x) I get this message.

```bash
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.6

Please only submit bug reports when using the officially supported version.
```

But vue's repo's packages.json do not mention any limitations regarding the typescript version to be used with.

Three weeks ago, `typescript-eslint` [released the v6.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v6.0.0) and `eslint-config-airbnb-typescript` followed right after with [the v17.1.0](https://github.com/iamturns/eslint-config-airbnb-typescript/releases/tag/v17.1.0).

Unlike [what `eslint-config-airbnb-typescript` did]( https://github.com/iamturns/eslint-config-airbnb-typescript/commit/8ef77c928c97d977f053c9c638831363a715d4a9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and because of `@rushstack/eslint-patch`, I personnally think this package should target the latest version only. But if so [rules breaking changes](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#rule-breaking-changes) should be mentionned in the release and therefore it might need a Major version bump (_ie_: v8.0.0).

What do you think @sodatea ?

**Comment by TradeMC** [comment]
Any updates? 🥺🥺🥺

**Comment by PurpleTape** [comment]
Any updates? 🥺🥺🥺

**Comment by frsimond** [comment]
@PurpleTape I've tried to make a nice PR for this. But I am affraid to make opinionated decisions and I am really short on time for the moment.
I would rather have @sodatea or an regular vue maintener handle this :)

**Comment by undergroundwires** [comment]
This is blocking upgrading following dependencies for me:

- `vue/eslint-config-typescript
- `@typescript-eslint/eslint-plugin`
- `@typescript-eslint/parser`

Can we please take a look at this @sodatea ❤️? Your work is highly appreciated and it's very nice to provide this package to community. But it has gotten so outdated that it has become a blocker for our modern TypeScript development. I think it deserves some attention. Quoting [Vue.js homepage](https://vuejs.org/guide/typescript/overview.html):

> Vue is written in TypeScript itself and provides **first-class TypeScript support**.

**Comment by everyx** [comment]
There is a workaround if you're using PNPM, you can use PNPM overrides to force using version 6.x:
Add to your package.json:

```json
 "pnpm": {
    "overrides": {
      "@typescript-eslint/parser": "6.9.0"
    }
  }
```

Then run pnpm install again
